server {
    listen 80;
    listen [::]:80;
    server_name zdorovzeya.work.gd www.zdorovzeya.work.gd;

    return 301 https://zdorovyezeya.ru$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name zdorovzeya.work.gd www.zdorovzeya.work.gd;

    ssl_certificate /etc/letsencrypt/live/zdorovzeya.work.gd/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/zdorovzeya.work.gd/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    return 301 https://zdorovyezeya.ru$request_uri;
}
